subscription_id = "###############"
client_id = "##############"
client_secret = "############"
tenant_id = "############"
seg1 = ""
seg2 = ""
seg3 = ""
rsg_count = n # number of resource groups to be provisioned
location = ["westus", "eastus"]